language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: '7.1'
      env: TARGET=phpunit

before_script:
  - composer self-update
  - composer install

script:
  - if [ "$TARGET" = "phpunit" ]; then composer install; fi
  - if [ "$TARGET" = "phpunit" ]; then phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover; fi
  - if [ "$TARGET" = "phpunit" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TARGET" = "phpunit" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi