user:
    path:     /user
    defaults: { _controller: AppBundle:User:index }

user_create:
    path:     /user/create
    defaults: { _controller: AppBundle:User:create }
    methods: [GET, POST]

user_edit:
    path:     /user/{id}
    defaults: { _controller: AppBundle:User:edit }
    methods: [PUT]
    requirements:
      id: '\d+'

user_delete:
    path:     /user/{id}
    defaults: { _controller: AppBundle:User:delete }
    methods: [DELETE]
    requirements:
      id: '\d+'
