user:
    path:     /user
    defaults: { _controller: AppBundle:User:index }

user_create:
    path:     /user/create
    defaults: { _controller: AppBundle:User:create }
    methods: [GET, POST]

user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: AppBundle:User:edit }
    methods: [GET, POST]
    requirements:
      id: '\d+'
